### ISSUE TITLE
fix semaphore ci

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#188]

**Comment by M4R1KU** [comment]
Fix circle too...

**Comment by jmesserli** [comment]
lol ya when I figure out why the stuff is broken I will

**Comment by jmesserli** [comment]
Since Semaphore and Circle are closed systems and acting weird, I'm going to try out a few self hosted CIs
What I have in mind:
- [BuildBot](https://buildbot.net/) No fancy UI but rock-solid, codeable CI. Used by [a lot of big projects](http://trac.buildbot.net/wiki/SuccessStories).
- [Concourse](https://concourse.ci/) [Super fancy UI](https://ci.concourse.ci/teams/main/pipelines/main?groups=develop), docker-based, docs seem alright, looks like a pita to configure build tasks
- [Buddy](https://buddy.works/) Neat UI, docker-based, easily configurable through ui, pricing is not in our range if the free version is not enough
- [Drone](https://github.com/drone/drone) Minimal UI, very easy setup, docker-based
- [Jenkins with Blue Ocean](https://jenkins.io/doc/book/blueocean/getting-started/#blueocean-docker) Actually really easy to set up with docker, uses a "Jenkinsfile" now, pretty usable ui with blue ocean

**Comment by M4R1KU** [comment]
They look all good but I would go with something that does not limit us in terms of pricing/free. 

Also I would prefer something easy because CI should not be the challenge in our project.
It should also be able to make an automated deployment.

- BuildBot: Does not look that bad actually (UI/ at least what I have seen) and we can also be sure that does what it is supposed to do.
- Concourse: Yep super fancy UI. What do mean by "looks like a pita to configure"?
- Buddy: Looks also very good and definetly follows our needs. Could be limiting sometime...
- Drone: Seems to be very easy but as far as I read the docs they do not have all features we'd need and are also in beta status currently and probably it would be better if we do not integrate more betas 🤔
- Jenkins: I'm not really a jenkins guy but with Blue Ocean it seems to be a better

**Comment by jmesserli** [comment]
With "looks like a pita to configure" I mean that I looked at their docs and it seemed kind of hard to configure the build steps. (Needing multiple files for multiple steps and so on).

I'm currently in favour of Jenkins, the new pipelines and blue ocean together are super easy to configure from what I've seen. Installation is just one docker container too.
Still looking at BuildBot too, but it seems like that would be like a side-project since we need to code the build first, and I would rather focus on our main product.

**Comment by M4R1KU** [comment]
Sounds good. Let's do it this way.

**Comment by jmesserli** [comment]
A Jenkins instance is up and running at https://ci.pegnu.cloud (you can use your Github login). The permissions are kind of funky so if you can't access something just tell me.
The build is currently failing but I figured out why this is (the Jenkins image uses Alpine Linux which is missing some libraries that nodejs needs, leading to a very useful "No such file or directory" error). This can be fixed by running the build itself in its own Docker image which I'll be setting up next.

**Comment by jmesserli** [comment]
TODO @me : Create own blueocean image, install docker, create docker group, add jenkins user to docker group

**Comment by jmesserli** [comment]
Update: Fixed frontend build by using an external agent (running at my home).
Next step is to add config files to the build process.
