### ISSUE TITLE
Failing builds because of timeout in docker rm

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#225]
There are builds that are all green until the end when they turn red because jenkins fails to remove a docker container.

This is a known bug and tracked in [JENKINS-42322](https://issues.jenkins-ci.org/browse/JENKINS-42322).

Opening this issue to have a link to the issue and raise awareness for @outcobra/developers.

**Comment by needToRoll** [comment]
The number of builds that are failing because of this issue seems to have increased.

According to [this comment](https://issues.jenkins-ci.org/browse/JENKINS-42322?focusedCommentId=299858&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-299858) someone built a snapshot with a temporary fix by increasing the time before timeout to five minutes.  But on the [pull request on GitHub](https://github.com/jenkinsci/docker-workflow-plugin/pull/100#issuecomment-301770829) I read that this is "fighting the symtoms without curing the desease".

What do you think we should do about that?

**Comment by jmesserli** [comment]
We wait until it's fixed in the offical plugin. In the meantime you have to look on Jenkins if the build actually failed or if it's just Docker.

**Comment by jmesserli** [comment]
The issue has been resolved and should be fixed in the next release. We can have green builds again! :P

**Comment by jmesserli** [comment]
Installed the self-built plugin with the fix a long time ago. Builds are no longer failing because of docker.
