### ISSUE TITLE
Marks UI Read Endpoint

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#236]
- [x] Define Dto
- [x] Implement Endpoint
- [ ] Do #231

**Comment by needToRoll** [comment]
Based on our current database design a mark (MarkValue) is linked to the subject over a specific markGroup that contains all marks of the given subject.

The question that opens up is if we want to use the same structure for the frontend.
As long as we dom't support nested groups I would recomand not to do so.


A DTO like this would work for now: 
```
{
	"subjectId": 1,
	"semesterId": 2,
	"weight": 0.5,
	"value": 5.5
}
```
BUT we need to be aware that this will lead to a big refactoring if we want to add grouping.
What do you think @outcobra/developers?

**Comment by M4R1KU** [comment]
What is the usecase for this DTO you show here? (Frontend use)

**Comment by needToRoll** [comment]
Just a mark, the main entity, used for creation update and so on

**Comment by M4R1KU** [comment]
So your question is to ignore the markgroups for the inital implementation?

**Comment by needToRoll** [comment]
Yes I consider it as an option

**Comment by M4R1KU** [comment]
I would bc I do not see a benefit or a simplification.

**Comment by jmesserli** [comment]
I think that's just ~ one line of code more in the frontend if we want to do a dumb implementation, so I'd vote against a simplified dto since we'll need the complete dto anyways.

**Comment by needToRoll** [comment]
ok:
How about this:
```
{
    "id":2,
    "marks":[
        {
            "id":5,
            "value":5.5,
            "weight":0.5,
            "markGroupId":2
        }
    ],
    "subjectId": 12,
	"examId": 0,
    "nestedGroups":[
        {
			//another markGroup
        }
    ]
}
```

**Comment by M4R1KU** [comment]
I'm also against it like @jmesserli. I corrected my comment.
I have to take a closer look when I'm at home @needToRoll.

**Comment by needToRoll** [comment]
I know that @M4R1KU.  That's why I added a second json in the first place

**Comment by needToRoll** [comment]
After a short discussion @M4R1KU and I agreed on [this structure for the Dto's](https://gist.github.com/needToRoll/8dbcc485765e457a39e185202453ec89)

**Comment by jmesserli** [comment]
And where's the semester id?

**Comment by needToRoll** [comment]
On line 2 inside the SemesterMarkDto?!

**Comment by jmesserli** [comment]
We'll have a talk

**Comment by needToRoll** [comment]
Ok then, sounds serious 😂

**Comment by jmesserli** [comment]
It's not but I don't understand how you are going to validate things

**Comment by needToRoll** [comment]
Ok we'll see

**Comment by jmesserli** [comment]
I just had a good talk with @needToRoll. We have updated the dto definition on the [gist](https://gist.github.com/needToRoll/8dbcc485765e457a39e185202453ec89). *Which is still not final*

Apart from that we have discovered a problem with the current owner validation which occurrs when two mark groups point to each other as parents (infinite loop), see this professional illustration here:
![grafik](https://cloud.githubusercontent.com/assets/613138/26174852/0115a830-3b51-11e7-9dfa-dc45ee6b1c7e.png)
This can only happen if the user is a pleb and decides to fake dtos but is still a problem for our application as it wouldn't be great for performance if there was a thread just going at it with the db queries. To fix this, we'll add a maximum recursion depth to [ParentLinked.followToUser()](https://github.com/outcobra/outstanding-cobra/blob/develop/backend/src/main/kotlin/outcobra/server/util/Extensions.kt#L75). For our purposes a maximum recursion depth of 50 should be more than enough and still finish quickly.

Furthermore, the validation will be designed so that the general validation flow does not have to get a new special case. The getParentLinked thingy will return a parent MarkGroup id if it has one, otherwise the subjectId.

**Comment by needToRoll** [comment]
I just finishend implementing the mappers it would be nice if you could take a look @jmesserli @M4R1KU

**Comment by needToRoll** [comment]
A first version of the mark endpoint is implemented. I think there will be some changes in the future because it has not yet been tested or approved from frontend side.

This needs a review!

**Comment by needToRoll** [comment]
@jmesserli I need help regarding the implementation of the mark persistence. (There is a todo inside the MarkGroup class and I have no idea how to implement that.
