### ISSUE TITLE
Edit Dialog does not close on save when nothing has been changed

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#312]
Every edit dialog that contains a date can not be submitted without changing the date first.

I found this bug on Nereid while using Chrome. 
But I can confirm that this bug exists on Larissa as well.
I've successfully reproduced the bug in firefox as well.

Can someone else please confirm this issue?
I think we should fix this asap.

**Comment by jmesserli** [comment]
As far as I can tell, this is not a problem with dates and neither that the dialogs are dirty. They are actually **not** dirty if you don't change anything.
This is checked here : https://github.com/outcobra/outstanding-cobra/blob/develop/frontend/src/app/manage/semester-dialog/semester-dialog.component.ts#L57
which prevents submitting without changing anything.
The same thing applies to e.g. school classes, which don't have dates in them: https://github.com/outcobra/outstanding-cobra/blob/develop/frontend/src/app/manage/school-class-dialog/school-class-dialog.component.ts#L28

Apart from that, this is not really a high priority bug, because saving something that was not changed doesn't modify anything.

**Comment by M4R1KU** [comment]
Better title?

**Comment by M4R1KU** [comment]
Maybe your date is invalid because it is in the past? :thinking:

**Comment by M4R1KU** [comment]
Cannot reproduce
