### ISSUE TITLE
"super-service" for the client

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#71]
Make a super class for all services which handles basic stuff like the `baseUri` and has CRUD methods out of the box.

**Comment by M4R1KU** [comment]
The changes for this issue can be found in the commit [add core services for caching and crud](https://github.com/outcobra/outstanding-cobra/commit/ad0829807982b73ca57b6cc6052d32d3bba6370a)

**Comment by M4R1KU** [comment]
@needToRoll please review

**Comment by jmesserli** [comment]
As also mentioned [here](https://github.com/outcobra/outstanding-cobra/commit/0766faf2dea7f9f74ba60f410bef786f8539f758#commitcomment-20400059), I think this is not quite implemented yet in the way that I imagined. The service should already implement the functionality in a generic way instead of just providing an interface for services.
The implementing service should only have to override functions that are handled in a special way in this service

**Comment by M4R1KU** [comment]
@needToRoll do you want to implement it the way @jmesserli imagined it? It should be not really that hard to do that and very similar to the server.

**Comment by jmesserli** [comment]
Moved this to the next sprint, no point in rushing this in; it works as it is now. But if @needToRoll would like to take it thats good. Otherwise I'll do it.

**Comment by jmesserli** [comment]
_Note: we might be able to integrate #67 into this one (the super sevice could do checks)_
