### ISSUE TITLE
Build frontend with gradle

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#78]
The frontend should be built with gradle. This means we need a yarn binary on every system we build on.

- [x] Add `yarn` step for gradle
- [x] Add `ng build -prod` step to gradle
- [ ] Copy built files into backend resources so that it will be included in the `.war`
- [ ] Update CI-Configuration (yarn installation)

**Comment by jmesserli** [comment]
This needs a frontend fix first. The gradle build fails because ng build returns a non-zero exit code.

**Comment by jmesserli** [comment]
This is implemented all the way, it just needs that frontend fix, do you think this is appropriate for the QA-Sprint? @M4R1KU

**Comment by M4R1KU** [comment]
We'll see. If they don't fix it we'll just move it to the next sprint.

**Comment by needToRoll** [comment]
what frontend fix?

**Comment by M4R1KU** [comment]
It seems to be fixed but only with a shitty workaround but we can live with it.
Probably it will be fixed in a future realease of angular or angular-cli.
There is an issue on that topic from one of the angular-devs so i assume they will finally fix it...
[Here is the issue](https://github.com/angular/angular/issues/13853)
